project:
  type: default
  output-dir: _output
  render:
    - report.qmd
    - bcg-appendix-report.qmd

title: "Report: AIIM-Managerial Assignment"
subtitle: "Submitted by"
author:
  - name: >-
      \textbf{moveOptimizer}\tabularnewline[3pt]
      Franziska Eichmann, 7444012\tabularnewline[3pt]
      Tjorge Orlitz, 7443662\tabularnewline[3pt]
      Maike Katterbach, 7444323\tabularnewline[3pt]
      Lennart Jekel, 7444132\tabularnewline[3pt]
      Emre Selim Kosar, 7431316

bibliography: references.bib

format:
  pdf:
    pdf-engine: xelatex
    documentclass: scrreprt
    classoption: notitlepage
    papersize: a4
    geometry:
      - top=1in
      - right=1in
      - bottom=1in
      - left=1in
    fontsize: 11pt
    mainfont: "Times New Roman"
    sansfont: "Times New Roman"
    toc: false
    number-sections: true
    highlight-style: github
    include-in-header:
      - tex/template-layout.tex
      - tex/compact-title.tex
      - tex/continuous-chapters.tex

execute:
  echo: false
  warning: false
  freeze: auto
