import sqlite3
import os
import json

DB_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "mobility_advisor.db")

def get_connection():
    conn = sqlite3.connect(DB_FILE)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    conn = get_connection()
    cursor = conn.cursor()
    
    # 1. Users Table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS users (
        id TEXT PRIMARY KEY,
        db_customer_id TEXT UNIQUE NOT NULL,
        name TEXT NOT NULL,
        created_at TEXT NOT NULL,
        preferences TEXT NOT NULL, -- JSON string containing weights (cost_priority, co2_priority, etc.)
        consent_status TEXT NOT NULL -- JSON string containing email_opted_in, calendar_shared, etc.
    );
    """)

    # 2. Travel History Table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS travel_history (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        trip_date TEXT NOT NULL,
        origin TEXT NOT NULL,
        destination TEXT NOT NULL,
        mode TEXT NOT NULL, -- train, car, scooter, bus, etc.
        distance_km REAL NOT NULL,
        cost_eur REAL NOT NULL,
        co2_kg REAL NOT NULL,
        created_at TEXT NOT NULL,
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    );
    """)

    # 3. Current Subscriptions Table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS subscriptions (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        service TEXT NOT NULL, -- bahncard_25_2nd, deutschlandticket, miles, lime, etc.
        status TEXT NOT NULL, -- active, cancelled
        monthly_cost_eur REAL NOT NULL,
        renewal_date TEXT,
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    );
    """)

    # 4. Recommendations & Approvals Table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS recommendations (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        created_at TEXT NOT NULL,
        scenarios TEXT NOT NULL, -- JSON string containing ranked portfolios generated by optimizer
        status TEXT NOT NULL, -- analyzing, ready, approved, rejected
        approval_timestamp TEXT,
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    );
    """)

    # 5. Audit Log Table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS audit_log (
        id TEXT PRIMARY KEY,
        user_id TEXT,
        action TEXT NOT NULL,
        details TEXT NOT NULL, -- JSON string
        timestamp TEXT NOT NULL
    );
    """)

    # 6. Internal Pricing Catalog Table (for Optimizer)
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS pricing_catalog (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        monthly_cost REAL NOT NULL,
        discount_percent REAL NOT NULL,
        unlimited_trips INTEGER NOT NULL, -- 1 for True, 0 for False
        coverage TEXT NOT NULL
    );
    """)

    conn.commit()
    conn.close()

if __name__ == "__main__":
    init_db()
    print("Database initialized successfully at:", DB_FILE)
