"""
Subscription Products Catalogue seeder.

Sources:
  - data/subscription_overview.xlsx  (ÖPNV_Bahn, Bike_Sharing, E_Scooters sheets)
  - data/Markdownfiles Abos/         (car sharing + detailed pricing)

Adds missing columns to an existing DB before seeding, so it is safe to run
against both fresh and already-migrated databases.

Run standalone:
    uv run python db/seed_subscription_products.py

Or import:
    from db.seed_subscription_products import seed_products
    seed_products()
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from db.db_utils import execute, executemany, get_conn, init_db

# ---------------------------------------------------------------------------
# New columns — added via ALTER TABLE on existing DBs
# ---------------------------------------------------------------------------
NEW_COLUMNS: dict[str, str] = {
    "pricing_model":         "TEXT",
    "cost_per_minute_eur":   "REAL",
    "cost_per_km_eur":       "REAL",
    "unlock_fee_eur":        "REAL",
    "free_minutes_per_ride": "INTEGER",
    "period_days":           "INTEGER",
    "eligibility_min_age":   "INTEGER",
    "eligibility_max_age":   "INTEGER",
    "eligibility_notes":     "TEXT",
    "city_availability":     "TEXT",
    "markdown_ref":          "TEXT",
}

# Shorthand lists used in combinable_with
_ALL_BC = [
    "BC25-2", "BC25-2-PROBE", "MY-BC25-2", "BC25-2-SENIOR",
    "BC25-2-ERMAE", "BC25-2-ERMAE-PROBE", "BC25-JUGEND",
    "BC50-2", "BC50-2-PROBE", "MY-BC50-2", "BC50-2-SENIOR",
    "BC50-2-ERMAE", "BC50-2-ERMAE-PROBE",
    "BC100-2", "BC100-2-PROBE", "MY-BC100-2",
]
_DT = ["DT-49", "DT-JOB"]

# ---------------------------------------------------------------------------
# Product catalogue
# ---------------------------------------------------------------------------
# Each dict must contain exactly the keys listed in COLUMNS below.
PRODUCTS: list[dict] = [
    # =========================================================================
    # ÖPNV / Bahn
    # =========================================================================
    {
        "product_id": "DT-49",
        "product_name": "Deutschlandticket",
        "type": "subscription",
        "monthly_cost_eur": 63.0,
        "annual_cost_eur": 756.0,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "nationwide_regional",
        "valid_modes": ["bus", "tram", "subway", "regional_train", "shared_bike"],
        "min_commitment_months": 1,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": _ALL_BC,
        "is_active": 1,
        "notes": "Gilt im gesamten ÖPNV (Bus, Tram, U-Bahn, S-Bahn, RE, RB). Kündigung bis 10. des Monats zum Monatsende.",
        "pricing_model": "flat_monthly",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 30,
        "eligibility_min_age": None,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "bundesweit",
        "markdown_ref": "Markdownfiles Abos/ÖPNV_Bahncards/Deutschlandticket/deutschlandticket_tarifbestimmungen.md",
    },
    {
        "product_id": "DT-JOB",
        "product_name": "Deutschlandticket Jobticket",
        "type": "subscription",
        "monthly_cost_eur": 44.10,
        "annual_cost_eur": 529.20,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "nationwide_regional",
        "valid_modes": ["bus", "tram", "subway", "regional_train", "shared_bike"],
        "min_commitment_months": 1,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": _ALL_BC,
        "is_active": 1,
        "notes": "Arbeitgeber zahlt mind. 25 % Zuschuss. Mitarbeiterpreis max. 44,10 €/Monat (Stand Jan 2026).",
        "pricing_model": "flat_monthly",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 30,
        "eligibility_min_age": None,
        "eligibility_max_age": None,
        "eligibility_notes": "Nur über Arbeitgeber erhältlich; Arbeitgeber muss Jobticket-Vertrag abgeschlossen haben.",
        "city_availability": "bundesweit",
        "markdown_ref": None,
    },
    # ── BahnCard 25 ──────────────────────────────────────────────────────────
    {
        "product_id": "BC25-2",
        "product_name": "BahnCard 25, 2. Klasse",
        "type": "card",
        "monthly_cost_eur": round(62.90 / 12, 2),
        "annual_cost_eur": 62.90,
        "discount_pct": 25.0,
        "travel_class": 2,
        "coverage_scope": "nationwide_long_distance",
        "valid_modes": ["regional_train", "long_distance_train"],
        "min_commitment_months": 12,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": _DT,
        "is_active": 1,
        "notes": "25 % Rabatt auf Flex-, Spar- und Super-Sparpreis. 1. Klasse: 125,00 €/Jahr.",
        "pricing_model": "flat_monthly",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 365,
        "eligibility_min_age": 27,
        "eligibility_max_age": 64,
        "eligibility_notes": None,
        "city_availability": "bundesweit",
        "markdown_ref": "Markdownfiles Abos/ÖPNV_Bahncards/Bahncard 25/bahncard25_2klasse.md",
    },
    {
        "product_id": "BC25-2-PROBE",
        "product_name": "Probe BahnCard 25, 2. Klasse",
        "type": "card",
        "monthly_cost_eur": round(19.90 / 3, 2),
        "annual_cost_eur": 19.90,
        "discount_pct": 25.0,
        "travel_class": 2,
        "coverage_scope": "nationwide_long_distance",
        "valid_modes": ["regional_train", "long_distance_train"],
        "min_commitment_months": 3,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": _DT,
        "is_active": 1,
        "notes": "3 Monate, dann automatisch Übergang in reguläre BC25 falls nicht gekündigt. 1. Klasse: 39,90 €.",
        "pricing_model": "flat_monthly",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 90,
        "eligibility_min_age": 27,
        "eligibility_max_age": 64,
        "eligibility_notes": None,
        "city_availability": "bundesweit",
        "markdown_ref": "Markdownfiles Abos/ÖPNV_Bahncards/Bahncard 25/bahncard25_2klasse.md",
    },
    {
        "product_id": "MY-BC25-2",
        "product_name": "My BahnCard 25, 2. Klasse",
        "type": "card",
        "monthly_cost_eur": round(39.90 / 12, 2),
        "annual_cost_eur": 39.90,
        "discount_pct": 25.0,
        "travel_class": 2,
        "coverage_scope": "nationwide_long_distance",
        "valid_modes": ["regional_train", "long_distance_train"],
        "min_commitment_months": 12,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": _DT,
        "is_active": 1,
        "notes": "Für Fahrgäste von 18–26 Jahren. 1. Klasse: 81,90 €/Jahr.",
        "pricing_model": "flat_monthly",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 365,
        "eligibility_min_age": 18,
        "eligibility_max_age": 26,
        "eligibility_notes": "Für Fahrgäste zwischen 18 und 26 Jahren.",
        "city_availability": "bundesweit",
        "markdown_ref": "Markdownfiles Abos/ÖPNV_Bahncards/Bahncard 25/bahncard25_uebersicht.md",
    },
    {
        "product_id": "BC25-2-SENIOR",
        "product_name": "Senioren BahnCard 25, 2. Klasse",
        "type": "card",
        "monthly_cost_eur": round(40.90 / 12, 2),
        "annual_cost_eur": 40.90,
        "discount_pct": 25.0,
        "travel_class": 2,
        "coverage_scope": "nationwide_long_distance",
        "valid_modes": ["regional_train", "long_distance_train"],
        "min_commitment_months": 12,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": _DT,
        "is_active": 1,
        "notes": "Für Fahrgäste ab 65 Jahren. 1. Klasse: 81,90 €/Jahr.",
        "pricing_model": "flat_monthly",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 365,
        "eligibility_min_age": 65,
        "eligibility_max_age": None,
        "eligibility_notes": "Für Fahrgäste ab 65 Jahren.",
        "city_availability": "bundesweit",
        "markdown_ref": "Markdownfiles Abos/ÖPNV_Bahncards/Bahncard 25/bahncard25_uebersicht.md",
    },
    {
        "product_id": "BC25-2-ERMAE",
        "product_name": "Ermäßigte BahnCard 25, 2. Klasse",
        "type": "card",
        "monthly_cost_eur": round(40.90 / 12, 2),
        "annual_cost_eur": 40.90,
        "discount_pct": 25.0,
        "travel_class": 2,
        "coverage_scope": "nationwide_long_distance",
        "valid_modes": ["regional_train", "long_distance_train"],
        "min_commitment_months": 12,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": _DT,
        "is_active": 1,
        "notes": "1. Klasse: 81,90 €/Jahr.",
        "pricing_model": "flat_monthly",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 365,
        "eligibility_min_age": None,
        "eligibility_max_age": 64,
        "eligibility_notes": "Für Schwerbehinderte (GdB ≥ 70) oder Bezieher voller Erwerbsminderungsrente (bis 64 J.).",
        "city_availability": "bundesweit",
        "markdown_ref": "Markdownfiles Abos/ÖPNV_Bahncards/Bahncard 25/bahncard25_uebersicht.md",
    },
    {
        "product_id": "BC25-2-ERMAE-PROBE",
        "product_name": "Ermäßigte Probe BahnCard 25, 2. Klasse",
        "type": "card",
        "monthly_cost_eur": round(19.90 / 3, 2),
        "annual_cost_eur": 19.90,
        "discount_pct": 25.0,
        "travel_class": 2,
        "coverage_scope": "nationwide_long_distance",
        "valid_modes": ["regional_train", "long_distance_train"],
        "min_commitment_months": 3,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": _DT,
        "is_active": 1,
        "notes": "3 Monate, dann Übergang in Ermäßigte BC25. 1. Klasse: 39,90 €.",
        "pricing_model": "flat_monthly",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 90,
        "eligibility_min_age": None,
        "eligibility_max_age": 64,
        "eligibility_notes": "Für Schwerbehinderte (GdB ≥ 70) oder Bezieher voller Erwerbsminderungsrente (bis 64 J.).",
        "city_availability": "bundesweit",
        "markdown_ref": "Markdownfiles Abos/ÖPNV_Bahncards/Bahncard 25/bahncard25_uebersicht.md",
    },
    {
        "product_id": "BC25-JUGEND",
        "product_name": "Jugend BahnCard 25",
        "type": "card",
        "monthly_cost_eur": round(7.90 / 12, 2),
        "annual_cost_eur": 7.90,
        "discount_pct": 25.0,
        "travel_class": None,
        "coverage_scope": "nationwide_long_distance",
        "valid_modes": ["regional_train", "long_distance_train"],
        "min_commitment_months": 12,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": ["DT-49"],
        "is_active": 1,
        "notes": "Gilt für 1. und 2. Klasse. Endet automatisch nach 12 Monaten, keine Kündigung nötig.",
        "pricing_model": "flat_monthly",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 365,
        "eligibility_min_age": 6,
        "eligibility_max_age": 18,
        "eligibility_notes": "Für Kinder und Jugendliche von 6 bis 18 Jahren.",
        "city_availability": "bundesweit",
        "markdown_ref": "Markdownfiles Abos/ÖPNV_Bahncards/Bahncard 25/bahncard25_uebersicht.md",
    },
    # ── BahnCard 50 ──────────────────────────────────────────────────────────
    {
        "product_id": "BC50-2",
        "product_name": "BahnCard 50, 2. Klasse",
        "type": "card",
        "monthly_cost_eur": round(244.0 / 12, 2),
        "annual_cost_eur": 244.0,
        "discount_pct": 50.0,
        "travel_class": 2,
        "coverage_scope": "nationwide_long_distance",
        "valid_modes": ["regional_train", "long_distance_train"],
        "min_commitment_months": 12,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": _DT,
        "is_active": 1,
        "notes": "50 % Rabatt auf Flexpreis, 25 % auf Sparpreise.",
        "pricing_model": "flat_monthly",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 365,
        "eligibility_min_age": 27,
        "eligibility_max_age": 64,
        "eligibility_notes": None,
        "city_availability": "bundesweit",
        "markdown_ref": None,
    },
    {
        "product_id": "BC50-2-PROBE",
        "product_name": "Probe BahnCard 50, 2. Klasse",
        "type": "card",
        "monthly_cost_eur": round(76.90 / 3, 2),
        "annual_cost_eur": 76.90,
        "discount_pct": 50.0,
        "travel_class": 2,
        "coverage_scope": "nationwide_long_distance",
        "valid_modes": ["regional_train", "long_distance_train"],
        "min_commitment_months": 3,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": _DT,
        "is_active": 1,
        "notes": "3 Monate, dann Übergang in reguläre BC50.",
        "pricing_model": "flat_monthly",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 90,
        "eligibility_min_age": 27,
        "eligibility_max_age": 64,
        "eligibility_notes": None,
        "city_availability": "bundesweit",
        "markdown_ref": None,
    },
    {
        "product_id": "MY-BC50-2",
        "product_name": "My BahnCard 50, 2. Klasse",
        "type": "card",
        "monthly_cost_eur": round(64.99 / 12, 2),
        "annual_cost_eur": 64.99,
        "discount_pct": 50.0,
        "travel_class": 2,
        "coverage_scope": "nationwide_long_distance",
        "valid_modes": ["regional_train", "long_distance_train"],
        "min_commitment_months": 12,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": _DT,
        "is_active": 1,
        "notes": "Für Fahrgäste von 18–26 Jahren.",
        "pricing_model": "flat_monthly",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 365,
        "eligibility_min_age": 18,
        "eligibility_max_age": 26,
        "eligibility_notes": "Für Fahrgäste zwischen 18 und 26 Jahren.",
        "city_availability": "bundesweit",
        "markdown_ref": None,
    },
    {
        "product_id": "BC50-2-SENIOR",
        "product_name": "Senioren BahnCard 50, 2. Klasse",
        "type": "card",
        "monthly_cost_eur": round(99.0 / 12, 2),
        "annual_cost_eur": 99.0,
        "discount_pct": 50.0,
        "travel_class": 2,
        "coverage_scope": "nationwide_long_distance",
        "valid_modes": ["regional_train", "long_distance_train"],
        "min_commitment_months": 12,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": _DT,
        "is_active": 1,
        "notes": "Für Fahrgäste ab 65 Jahren.",
        "pricing_model": "flat_monthly",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 365,
        "eligibility_min_age": 65,
        "eligibility_max_age": None,
        "eligibility_notes": "Für Fahrgäste ab 65 Jahren.",
        "city_availability": "bundesweit",
        "markdown_ref": None,
    },
    {
        "product_id": "BC50-2-ERMAE",
        "product_name": "Ermäßigte BahnCard 50, 2. Klasse",
        "type": "card",
        "monthly_cost_eur": round(99.0 / 12, 2),
        "annual_cost_eur": 99.0,
        "discount_pct": 50.0,
        "travel_class": 2,
        "coverage_scope": "nationwide_long_distance",
        "valid_modes": ["regional_train", "long_distance_train"],
        "min_commitment_months": 12,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": _DT,
        "is_active": 1,
        "notes": None,
        "pricing_model": "flat_monthly",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 365,
        "eligibility_min_age": None,
        "eligibility_max_age": 64,
        "eligibility_notes": "Für Schwerbehinderte (GdB ≥ 70) oder Bezieher voller Erwerbsminderungsrente (bis 64 J.).",
        "city_availability": "bundesweit",
        "markdown_ref": None,
    },
    {
        "product_id": "BC50-2-ERMAE-PROBE",
        "product_name": "Ermäßigte Probe BahnCard 50, 2. Klasse",
        "type": "card",
        "monthly_cost_eur": round(76.90 / 3, 2),
        "annual_cost_eur": 76.90,
        "discount_pct": 50.0,
        "travel_class": 2,
        "coverage_scope": "nationwide_long_distance",
        "valid_modes": ["regional_train", "long_distance_train"],
        "min_commitment_months": 3,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": _DT,
        "is_active": 1,
        "notes": "3 Monate, dann Übergang in Ermäßigte BC50.",
        "pricing_model": "flat_monthly",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 90,
        "eligibility_min_age": None,
        "eligibility_max_age": 64,
        "eligibility_notes": "Für Schwerbehinderte (GdB ≥ 70) oder Bezieher voller Erwerbsminderungsrente (bis 64 J.).",
        "city_availability": "bundesweit",
        "markdown_ref": None,
    },
    # ── BahnCard 100 ─────────────────────────────────────────────────────────
    {
        "product_id": "BC100-2",
        "product_name": "BahnCard 100, 2. Klasse",
        "type": "subscription",
        "monthly_cost_eur": round(4899.0 / 12, 2),
        "annual_cost_eur": 4899.0,
        "discount_pct": 100.0,
        "travel_class": 2,
        "coverage_scope": "nationwide_all_train",
        "valid_modes": ["regional_train", "long_distance_train"],
        "min_commitment_months": 12,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": [],
        "is_active": 1,
        "notes": "Unbegrenzt Reisen im Fern- und Nahverkehr der DB, 2. Klasse.",
        "pricing_model": "flat_monthly",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 365,
        "eligibility_min_age": 27,
        "eligibility_max_age": 64,
        "eligibility_notes": None,
        "city_availability": "bundesweit",
        "markdown_ref": None,
    },
    {
        "product_id": "BC100-2-PROBE",
        "product_name": "Probe BahnCard 100, 2. Klasse",
        "type": "subscription",
        "monthly_cost_eur": round(1459.0 / 3, 2),
        "annual_cost_eur": 1459.0,
        "discount_pct": 100.0,
        "travel_class": 2,
        "coverage_scope": "nationwide_all_train",
        "valid_modes": ["regional_train", "long_distance_train"],
        "min_commitment_months": 3,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": [],
        "is_active": 1,
        "notes": "3 Monate, dann Übergang in reguläre BC100.",
        "pricing_model": "flat_monthly",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 90,
        "eligibility_min_age": 27,
        "eligibility_max_age": 64,
        "eligibility_notes": None,
        "city_availability": "bundesweit",
        "markdown_ref": None,
    },
    {
        "product_id": "MY-BC100-2",
        "product_name": "My BahnCard 100, 2. Klasse",
        "type": "subscription",
        "monthly_cost_eur": round(3199.0 / 12, 2),
        "annual_cost_eur": 3199.0,
        "discount_pct": 100.0,
        "travel_class": 2,
        "coverage_scope": "nationwide_all_train",
        "valid_modes": ["regional_train", "long_distance_train"],
        "min_commitment_months": 12,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": [],
        "is_active": 1,
        "notes": "Für Fahrgäste von 18–26 Jahren.",
        "pricing_model": "flat_monthly",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 365,
        "eligibility_min_age": 18,
        "eligibility_max_age": 26,
        "eligibility_notes": "Für Fahrgäste zwischen 18 und 26 Jahren.",
        "city_availability": "bundesweit",
        "markdown_ref": None,
    },

    # =========================================================================
    # Bike Sharing
    # =========================================================================
    # ── Call a Bike (DB Connect) ──────────────────────────────────────────────
    {
        "product_id": "CALLABIKE-STARTER",
        "product_name": "Call a Bike Starter",
        "type": "pass",
        "monthly_cost_eur": 0.0,
        "annual_cost_eur": 0.0,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_bike"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": ["DT-49"],
        "is_active": 1,
        "notes": "Keine Grundgebühr. 1,00 € Freischaltung + 0,12 €/min. Tageshöchstpreis 13,00 €.",
        "pricing_model": "per_minute",
        "cost_per_minute_eur": 0.12,
        "cost_per_km_eur": None,
        "unlock_fee_eur": 1.00,
        "free_minutes_per_ride": 0,
        "period_days": None,
        "eligibility_min_age": None,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Berlin, Hamburg, München, Frankfurt, Köln, Stuttgart und weitere Großstädte",
        "markdown_ref": "Markdownfiles Abos/Bike Sharing/callabike/callabike_preisverzeichnis.md",
    },
    {
        "product_id": "CALLABIKE-MEMBER",
        "product_name": "Call a Bike Member",
        "type": "subscription",
        "monthly_cost_eur": round(10.0 / 12, 2),
        "annual_cost_eur": 10.0,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_bike"],
        "min_commitment_months": 12,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": ["DT-49"],
        "is_active": 1,
        "notes": "10 €/Jahr. Keine Freischaltgebühr. 0,10 €/min. Tageshöchstpreis 10,00 €.",
        "pricing_model": "hybrid",
        "cost_per_minute_eur": 0.10,
        "cost_per_km_eur": None,
        "unlock_fee_eur": 0.0,
        "free_minutes_per_ride": 0,
        "period_days": 365,
        "eligibility_min_age": None,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Berlin, Hamburg, München, Frankfurt, Köln, Stuttgart und weitere Großstädte",
        "markdown_ref": "Markdownfiles Abos/Bike Sharing/callabike/callabike_preisverzeichnis.md",
    },
    {
        "product_id": "CALLABIKE-MEMBERPLUS",
        "product_name": "Call a Bike Member Plus",
        "type": "subscription",
        "monthly_cost_eur": 8.0,
        "annual_cost_eur": 96.0,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_bike"],
        "min_commitment_months": 12,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": ["DT-49"],
        "is_active": 1,
        "notes": "8 €/Monat (96 €/Jahr). 30 Freiminuten pro Fahrt, danach 0,10 €/min. Tageshöchstpreis 10,00 €.",
        "pricing_model": "hybrid",
        "cost_per_minute_eur": 0.10,
        "cost_per_km_eur": None,
        "unlock_fee_eur": 0.0,
        "free_minutes_per_ride": 30,
        "period_days": 30,
        "eligibility_min_age": None,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Berlin, Hamburg, München, Frankfurt, Köln, Stuttgart und weitere Großstädte",
        "markdown_ref": "Markdownfiles Abos/Bike Sharing/callabike/callabike_preisverzeichnis.md",
    },
    # ── Nextbike ──────────────────────────────────────────────────────────────
    {
        "product_id": "NEXTBIKE-BASIC",
        "product_name": "Nextbike Pay-as-you-go",
        "type": "pass",
        "monthly_cost_eur": 0.0,
        "annual_cost_eur": 0.0,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_bike"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": ["DT-49"],
        "is_active": 1,
        "notes": "Keine Grundgebühr. 1,00 €/15 min, danach weitere 1,00 €/30 min.",
        "pricing_model": "per_minute",
        "cost_per_minute_eur": round(1.0 / 15, 4),
        "cost_per_km_eur": None,
        "unlock_fee_eur": 0.0,
        "free_minutes_per_ride": 0,
        "period_days": None,
        "eligibility_min_age": None,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Über 300 Städte in Deutschland",
        "markdown_ref": None,
    },
    {
        "product_id": "NEXTBIKE-MONAT",
        "product_name": "Nextbike Monatsabo",
        "type": "subscription",
        "monthly_cost_eur": 10.0,
        "annual_cost_eur": 120.0,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_bike"],
        "min_commitment_months": 1,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": ["DT-49"],
        "is_active": 1,
        "notes": "10 €/Monat. 30 Freiminuten pro Fahrt, danach 1,00 €/30 min.",
        "pricing_model": "hybrid",
        "cost_per_minute_eur": round(1.0 / 30, 4),
        "cost_per_km_eur": None,
        "unlock_fee_eur": 0.0,
        "free_minutes_per_ride": 30,
        "period_days": 30,
        "eligibility_min_age": None,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Über 300 Städte in Deutschland",
        "markdown_ref": None,
    },
    {
        "product_id": "NEXTBIKE-JAHR",
        "product_name": "Nextbike Jahresabo",
        "type": "subscription",
        "monthly_cost_eur": 5.0,
        "annual_cost_eur": 60.0,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_bike"],
        "min_commitment_months": 12,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": ["DT-49"],
        "is_active": 1,
        "notes": "60 €/Jahr (5 €/Monat). 30 Freiminuten pro Fahrt, danach 1,00 €/30 min.",
        "pricing_model": "hybrid",
        "cost_per_minute_eur": round(1.0 / 30, 4),
        "cost_per_km_eur": None,
        "unlock_fee_eur": 0.0,
        "free_minutes_per_ride": 30,
        "period_days": 365,
        "eligibility_min_age": None,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Über 300 Städte in Deutschland",
        "markdown_ref": None,
    },
    # ── Swapfiets ─────────────────────────────────────────────────────────────
    {
        "product_id": "SWAPFIETS-STADTRAD",
        "product_name": "Swapfiets Stadtrad",
        "type": "subscription",
        "monthly_cost_eur": 15.90,
        "annual_cost_eur": 190.80,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_bike"],
        "min_commitment_months": 1,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": ["DT-49"],
        "is_active": 1,
        "notes": "Monatliches Fahrrad-Abo (kein Sharing). Wartung und Pannenhilfe inklusive.",
        "pricing_model": "flat_monthly",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 30,
        "eligibility_min_age": None,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Berlin, Hamburg, München, Köln, Frankfurt, Düsseldorf und weitere",
        "markdown_ref": None,
    },
    {
        "product_id": "SWAPFIETS-EBIKE-P1",
        "product_name": "Swapfiets E-Bike Power 1",
        "type": "subscription",
        "monthly_cost_eur": 54.90,
        "annual_cost_eur": 658.80,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_bike"],
        "min_commitment_months": 1,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": ["DT-49"],
        "is_active": 1,
        "notes": "E-Bike Abo (kein Sharing). Wartung und Pannenhilfe inklusive.",
        "pricing_model": "flat_monthly",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 30,
        "eligibility_min_age": None,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Berlin, Hamburg, München, Köln, Frankfurt, Düsseldorf und weitere",
        "markdown_ref": None,
    },
    {
        "product_id": "SWAPFIETS-EBIKE-P7",
        "product_name": "Swapfiets E-Bike Power 7",
        "type": "subscription",
        "monthly_cost_eur": 64.90,
        "annual_cost_eur": 778.80,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_bike"],
        "min_commitment_months": 1,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": ["DT-49"],
        "is_active": 1,
        "notes": "Premium E-Bike Abo mit 7-Gang-Schaltung. Wartung und Pannenhilfe inklusive.",
        "pricing_model": "flat_monthly",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 30,
        "eligibility_min_age": None,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Berlin, Hamburg, München, Köln, Frankfurt, Düsseldorf und weitere",
        "markdown_ref": None,
    },

    # =========================================================================
    # E-Scooter
    # =========================================================================
    # ── Dott ─────────────────────────────────────────────────────────────────
    {
        "product_id": "DOTT-PAYG",
        "product_name": "Dott Pay-as-you-go",
        "type": "pass",
        "monthly_cost_eur": 0.0,
        "annual_cost_eur": 0.0,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": ["DT-49"],
        "is_active": 1,
        "notes": "0,49 € Freischaltung + 0,29 €/min.",
        "pricing_model": "per_minute",
        "cost_per_minute_eur": 0.29,
        "cost_per_km_eur": None,
        "unlock_fee_eur": 0.49,
        "free_minutes_per_ride": 0,
        "period_days": None,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Köln, Berlin, Hamburg und weitere Städte",
        "markdown_ref": None,
    },
    {
        "product_id": "DOTT-UNLOCK",
        "product_name": "Dott Freischaltungs-Abo",
        "type": "subscription",
        "monthly_cost_eur": 3.99,
        "annual_cost_eur": 47.88,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 1,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": ["DT-49"],
        "is_active": 1,
        "notes": "3,99 €/30 Tage. Keine Freischaltgebühr, 0,29 €/min.",
        "pricing_model": "hybrid",
        "cost_per_minute_eur": 0.29,
        "cost_per_km_eur": None,
        "unlock_fee_eur": 0.0,
        "free_minutes_per_ride": 0,
        "period_days": 30,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Köln, Berlin, Hamburg und weitere Städte",
        "markdown_ref": None,
    },
    {
        "product_id": "DOTT-FLEX",
        "product_name": "Dott Flex Pass",
        "type": "subscription",
        "monthly_cost_eur": 0.99,
        "annual_cost_eur": 11.88,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 1,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": ["DT-49"],
        "is_active": 1,
        "notes": "0,99 €/30 Tage. 1,80 € Freischaltgebühr pro Fahrt. 30 Freiminuten inklusive.",
        "pricing_model": "hybrid",
        "cost_per_minute_eur": 0.0,
        "cost_per_km_eur": None,
        "unlock_fee_eur": 1.80,
        "free_minutes_per_ride": 30,
        "period_days": 30,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Köln, Berlin, Hamburg und weitere Städte",
        "markdown_ref": None,
    },
    {
        "product_id": "DOTT-PRO",
        "product_name": "Dott Pro Pass",
        "type": "subscription",
        "monthly_cost_eur": 7.99,
        "annual_cost_eur": 95.88,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 1,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": ["DT-49"],
        "is_active": 1,
        "notes": "7,99 €/30 Tage. 1,00 € Freischaltgebühr pro Fahrt. 30 Freiminuten inklusive.",
        "pricing_model": "hybrid",
        "cost_per_minute_eur": 0.0,
        "cost_per_km_eur": None,
        "unlock_fee_eur": 1.00,
        "free_minutes_per_ride": 30,
        "period_days": 30,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Köln, Berlin, Hamburg und weitere Städte",
        "markdown_ref": None,
    },
    {
        "product_id": "DOTT-TP30",
        "product_name": "Dott Tagespass 30 min",
        "type": "pass",
        "monthly_cost_eur": None,
        "annual_cost_eur": None,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": [],
        "is_active": 1,
        "notes": "3,99 €. 30 Minuten. Gültig 1 Tag.",
        "pricing_model": "time_pass",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": 30,
        "period_days": 1,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Köln, Berlin, Hamburg und weitere Städte",
        "markdown_ref": None,
    },
    {
        "product_id": "DOTT-TP100",
        "product_name": "Dott Wochenpass 100 min",
        "type": "pass",
        "monthly_cost_eur": None,
        "annual_cost_eur": None,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": [],
        "is_active": 1,
        "notes": "12,99 €. 100 Minuten. Gültig 7 Tage.",
        "pricing_model": "time_pass",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": 100,
        "period_days": 7,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Köln, Berlin, Hamburg und weitere Städte",
        "markdown_ref": None,
    },
    # ── Voi ──────────────────────────────────────────────────────────────────
    {
        "product_id": "VOI-PAYG",
        "product_name": "Voi Pay-as-you-go",
        "type": "pass",
        "monthly_cost_eur": 0.0,
        "annual_cost_eur": 0.0,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": ["DT-49"],
        "is_active": 1,
        "notes": "Keine Grundgebühr, keine Freischaltgebühr. 0,30 €/min.",
        "pricing_model": "per_minute",
        "cost_per_minute_eur": 0.30,
        "cost_per_km_eur": None,
        "unlock_fee_eur": 0.0,
        "free_minutes_per_ride": 0,
        "period_days": None,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Köln, Berlin, Hamburg, Frankfurt und weitere Städte",
        "markdown_ref": None,
    },
    {
        "product_id": "VOI-PLUS",
        "product_name": "Voi Plus",
        "type": "subscription",
        "monthly_cost_eur": 0.99,
        "annual_cost_eur": 11.88,
        "discount_pct": 20.0,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 1,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": ["DT-49"],
        "is_active": 1,
        "notes": "0,99 €/30 Tage. Keine Freischaltgebühr. 0,24 €/min (20 % Rabatt ggü. PayG).",
        "pricing_model": "hybrid",
        "cost_per_minute_eur": 0.24,
        "cost_per_km_eur": None,
        "unlock_fee_eur": 0.0,
        "free_minutes_per_ride": 0,
        "period_days": 30,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Köln, Berlin, Hamburg, Frankfurt und weitere Städte",
        "markdown_ref": None,
    },
    {
        "product_id": "VOI-TP30",
        "product_name": "Voi Tagespass 30 min",
        "type": "pass",
        "monthly_cost_eur": None,
        "annual_cost_eur": None,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": [],
        "is_active": 1,
        "notes": "3,99 €. 30 Minuten. Gültig 1 Tag.",
        "pricing_model": "time_pass",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": 30,
        "period_days": 1,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Köln, Berlin, Hamburg, Frankfurt und weitere Städte",
        "markdown_ref": None,
    },
    {
        "product_id": "VOI-TP60",
        "product_name": "Voi 3-Tages-Pass 60 min",
        "type": "pass",
        "monthly_cost_eur": None,
        "annual_cost_eur": None,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": [],
        "is_active": 1,
        "notes": "6,99 €. 60 Minuten. Gültig 3 Tage.",
        "pricing_model": "time_pass",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": 60,
        "period_days": 3,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Köln, Berlin, Hamburg, Frankfurt und weitere Städte",
        "markdown_ref": None,
    },
    {
        "product_id": "VOI-TP120",
        "product_name": "Voi Wochenpass 120 min",
        "type": "pass",
        "monthly_cost_eur": None,
        "annual_cost_eur": None,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": [],
        "is_active": 1,
        "notes": "12,99 €. 120 Minuten. Gültig 7 Tage.",
        "pricing_model": "time_pass",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": 120,
        "period_days": 7,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Köln, Berlin, Hamburg, Frankfurt und weitere Städte",
        "markdown_ref": None,
    },
    {
        "product_id": "VOI-TP300",
        "product_name": "Voi Monatspass 300 min",
        "type": "pass",
        "monthly_cost_eur": 29.99,
        "annual_cost_eur": None,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": [],
        "is_active": 1,
        "notes": "29,99 €. 300 Minuten. Gültig 30 Tage.",
        "pricing_model": "time_pass",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": 300,
        "period_days": 30,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Köln, Berlin, Hamburg, Frankfurt und weitere Städte",
        "markdown_ref": None,
    },
    {
        "product_id": "VOI-TP750",
        "product_name": "Voi Monatspass 750 min",
        "type": "pass",
        "monthly_cost_eur": 63.99,
        "annual_cost_eur": None,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": [],
        "is_active": 1,
        "notes": "63,99 €. 750 Minuten. Gültig 30 Tage.",
        "pricing_model": "time_pass",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": 750,
        "period_days": 30,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Köln, Berlin, Hamburg, Frankfurt und weitere Städte",
        "markdown_ref": None,
    },
    # ── Lime ─────────────────────────────────────────────────────────────────
    {
        "product_id": "LIME-PAYG",
        "product_name": "Lime Pay-as-you-go",
        "type": "pass",
        "monthly_cost_eur": 0.0,
        "annual_cost_eur": 0.0,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": ["DT-49"],
        "is_active": 1,
        "notes": "1,00 € Freischaltung + 0,25 €/min.",
        "pricing_model": "per_minute",
        "cost_per_minute_eur": 0.25,
        "cost_per_km_eur": None,
        "unlock_fee_eur": 1.00,
        "free_minutes_per_ride": 0,
        "period_days": None,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Berlin, Hamburg, München, Frankfurt, Köln und weitere Städte",
        "markdown_ref": "Markdownfiles Abos/E-Scooter/lime/lime_pricing.md",
    },
    {
        "product_id": "LIME-PRIME",
        "product_name": "Lime Prime",
        "type": "subscription",
        "monthly_cost_eur": 0.99,
        "annual_cost_eur": 11.88,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 1,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": ["DT-49"],
        "is_active": 1,
        "notes": "0,99 €/Monat. Fahrten ≤5 min: 1,00 €. Fahrten ≤20 min: 1,50 €. Danach regulärer Minutentarif.",
        "pricing_model": "hybrid",
        "cost_per_minute_eur": 0.25,
        "cost_per_km_eur": None,
        "unlock_fee_eur": 0.0,
        "free_minutes_per_ride": 0,
        "period_days": 30,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Berlin, Hamburg, München, Frankfurt, Köln und weitere Städte",
        "markdown_ref": "Markdownfiles Abos/E-Scooter/lime/lime_pricing.md",
    },
    {
        "product_id": "LIME-TP30",
        "product_name": "Lime Pass S (30 min / 1 Tag)",
        "type": "pass",
        "monthly_cost_eur": None,
        "annual_cost_eur": None,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": [],
        "is_active": 1,
        "notes": "2,99 €. 30 Minuten. Gültig 1 Tag.",
        "pricing_model": "time_pass",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": 30,
        "period_days": 1,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Berlin, Hamburg, München, Frankfurt, Köln und weitere Städte",
        "markdown_ref": "Markdownfiles Abos/E-Scooter/lime/lime_pricing.md",
    },
    {
        "product_id": "LIME-TP60",
        "product_name": "Lime Pass M (60 min / 3 Tage)",
        "type": "pass",
        "monthly_cost_eur": None,
        "annual_cost_eur": None,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": [],
        "is_active": 1,
        "notes": "5,99 €. 60 Minuten. Gültig 3 Tage.",
        "pricing_model": "time_pass",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": 60,
        "period_days": 3,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Berlin, Hamburg, München, Frankfurt, Köln und weitere Städte",
        "markdown_ref": "Markdownfiles Abos/E-Scooter/lime/lime_pricing.md",
    },
    {
        "product_id": "LIME-TP120",
        "product_name": "Lime Pass L (120 min / 7 Tage)",
        "type": "pass",
        "monthly_cost_eur": None,
        "annual_cost_eur": None,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": [],
        "is_active": 1,
        "notes": "11,99 €. 120 Minuten. Gültig 7 Tage.",
        "pricing_model": "time_pass",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": 120,
        "period_days": 7,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Berlin, Hamburg, München, Frankfurt, Köln und weitere Städte",
        "markdown_ref": "Markdownfiles Abos/E-Scooter/lime/lime_pricing.md",
    },
    {
        "product_id": "LIME-TP300",
        "product_name": "Lime Pass XL (300 min / 30 Tage)",
        "type": "pass",
        "monthly_cost_eur": 29.99,
        "annual_cost_eur": None,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": [],
        "is_active": 1,
        "notes": "29,99 €. 300 Minuten. Gültig 30 Tage.",
        "pricing_model": "time_pass",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": 300,
        "period_days": 30,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Berlin, Hamburg, München, Frankfurt, Köln und weitere Städte",
        "markdown_ref": "Markdownfiles Abos/E-Scooter/lime/lime_pricing.md",
    },
    # ── Bolt ─────────────────────────────────────────────────────────────────
    {
        "product_id": "BOLT-UNLOCK",
        "product_name": "Bolt Freischaltungs-Abo",
        "type": "subscription",
        "monthly_cost_eur": 1.99,
        "annual_cost_eur": 23.88,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 1,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": ["DT-49"],
        "is_active": 1,
        "notes": "1,99 €/30 Tage. Keine Freischaltgebühr. 0,22 €/min.",
        "pricing_model": "hybrid",
        "cost_per_minute_eur": 0.22,
        "cost_per_km_eur": None,
        "unlock_fee_eur": 0.0,
        "free_minutes_per_ride": 0,
        "period_days": 30,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Berlin, Hamburg, Köln, München und weitere Städte",
        "markdown_ref": None,
    },
    {
        "product_id": "BOLT-TP30",
        "product_name": "Bolt Tagespass 30 min",
        "type": "pass",
        "monthly_cost_eur": None,
        "annual_cost_eur": None,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": [],
        "is_active": 1,
        "notes": "2,99 €. 30 Minuten. Gültig 1 Tag.",
        "pricing_model": "time_pass",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": 30,
        "period_days": 1,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Berlin, Hamburg, Köln, München und weitere Städte",
        "markdown_ref": None,
    },
    {
        "product_id": "BOLT-TP60",
        "product_name": "Bolt 3-Tages-Pass 60 min",
        "type": "pass",
        "monthly_cost_eur": None,
        "annual_cost_eur": None,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": [],
        "is_active": 1,
        "notes": "4,99 €. 60 Minuten. Gültig 3 Tage.",
        "pricing_model": "time_pass",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": 60,
        "period_days": 3,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Berlin, Hamburg, Köln, München und weitere Städte",
        "markdown_ref": None,
    },
    {
        "product_id": "BOLT-TP70",
        "product_name": "Bolt Wochenpass 70 min",
        "type": "pass",
        "monthly_cost_eur": None,
        "annual_cost_eur": None,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": [],
        "is_active": 1,
        "notes": "5,99 €. 70 Minuten. Gültig 7 Tage.",
        "pricing_model": "time_pass",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": 70,
        "period_days": 7,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Berlin, Hamburg, Köln, München und weitere Städte",
        "markdown_ref": None,
    },
    {
        "product_id": "BOLT-TP200",
        "product_name": "Bolt Monatspass 200 min",
        "type": "pass",
        "monthly_cost_eur": 14.99,
        "annual_cost_eur": None,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["shared_scooter"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": [],
        "is_active": 1,
        "notes": "14,99 €. 200 Minuten. Gültig 30 Tage.",
        "pricing_model": "time_pass",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": None,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": 200,
        "period_days": 30,
        "eligibility_min_age": 18,
        "eligibility_max_age": None,
        "eligibility_notes": None,
        "city_availability": "Berlin, Hamburg, Köln, München und weitere Städte",
        "markdown_ref": None,
    },

    # =========================================================================
    # Car Sharing
    # =========================================================================
    {
        "product_id": "MILES-PAYG",
        "product_name": "Miles Car Sharing",
        "type": "pass",
        "monthly_cost_eur": 0.0,
        "annual_cost_eur": 0.0,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["car_sharing"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": ["DT-49"],
        "is_active": 1,
        "notes": "Keine Grundgebühr. S-Klasse ab 0,79 €/km inkl. Fahrzeit. 1,00 € Freischaltung. Parken: 0,35 €/min. Stunden- und Tagespakete verfügbar.",
        "pricing_model": "per_km",
        "cost_per_minute_eur": None,
        "cost_per_km_eur": 0.79,
        "unlock_fee_eur": 1.00,
        "free_minutes_per_ride": None,
        "period_days": None,
        "eligibility_min_age": 21,
        "eligibility_max_age": None,
        "eligibility_notes": "Führerschein erforderlich. Mindestalter 21 Jahre.",
        "city_availability": "Hamburg, Berlin, Köln, München, Wien",
        "markdown_ref": "Markdownfiles Abos/Car Sharing/miles/miles_pricing.md",
    },
    {
        "product_id": "SIXT-SHARE-MIN",
        "product_name": "Sixt Share",
        "type": "pass",
        "monthly_cost_eur": 0.0,
        "annual_cost_eur": 0.0,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["car_sharing"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": ["DT-49"],
        "is_active": 1,
        "notes": "Keine Grundgebühr. Minutentarif ab 0,09 €/min + 0,95 € Freischaltung (dynamisches Pricing). km-Tarif ab 0,99 €/km alternativ verfügbar.",
        "pricing_model": "per_minute",
        "cost_per_minute_eur": 0.09,
        "cost_per_km_eur": None,
        "unlock_fee_eur": 0.95,
        "free_minutes_per_ride": None,
        "period_days": None,
        "eligibility_min_age": 21,
        "eligibility_max_age": None,
        "eligibility_notes": "Führerschein erforderlich. Mindestalter 21 J. (ggf. 25 J. für bestimmte Fahrzeugklassen).",
        "city_availability": "München, Berlin, Hamburg, Frankfurt, Stuttgart und weitere Großstädte",
        "markdown_ref": "Markdownfiles Abos/Car Sharing/sixt/sixt_share_preise.md",
    },
    {
        "product_id": "TEILAUTO-START",
        "product_name": "teilAuto Starttarif",
        "type": "pass",
        "monthly_cost_eur": 0.0,
        "annual_cost_eur": 0.0,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["car_sharing"],
        "min_commitment_months": 0,
        "cancellation_notice_months": 0,
        "auto_renews": 0,
        "combinable_with": ["DT-49"],
        "is_active": 1,
        "notes": "Kein Monatsgrundpreis. 25 € einmalig + 100 € Kaution. Kleine-Klasse: 2,88 €/h + 0,35 €/km (Rahmentarif +20 %). Kraftstoff im km-Preis inkl.",
        "pricing_model": "per_km_and_time",
        "cost_per_minute_eur": round(2.88 / 60, 4),
        "cost_per_km_eur": 0.35,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": None,
        "eligibility_min_age": 21,
        "eligibility_max_age": None,
        "eligibility_notes": "Führerschein erforderlich.",
        "city_availability": "Leipzig, Dresden, Halle, Erfurt, Magdeburg, Jena und weitere ostdeutsche Städte",
        "markdown_ref": "Markdownfiles Abos/Car Sharing/teilauto/teilauto_preise_tarife.md",
    },
    {
        "product_id": "TEILAUTO-RAHMEN",
        "product_name": "teilAuto Rahmentarif",
        "type": "subscription",
        "monthly_cost_eur": 6.0,
        "annual_cost_eur": 72.0,
        "discount_pct": None,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["car_sharing"],
        "min_commitment_months": 12,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": ["DT-49", "BC25-2", "BC50-2", "BC100-2"],
        "is_active": 1,
        "notes": "6 €/Monat (Nichtmitglieder) + 25 € einmalig + 100 € Kaution. Kleine-Klasse: 2,40 €/h + 0,29 €/km. Kraftstoff im km-Preis inkl. BahnCard-Inhaber erhalten Sonderkondition (3 €/Monat).",
        "pricing_model": "per_km_and_time",
        "cost_per_minute_eur": round(2.40 / 60, 4),
        "cost_per_km_eur": 0.29,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 30,
        "eligibility_min_age": 21,
        "eligibility_max_age": None,
        "eligibility_notes": "Führerschein erforderlich.",
        "city_availability": "Leipzig, Dresden, Halle, Erfurt, Magdeburg, Jena und weitere ostdeutsche Städte",
        "markdown_ref": "Markdownfiles Abos/Car Sharing/teilauto/teilauto_preise_tarife.md",
    },
    {
        "product_id": "TEILAUTO-VIEL",
        "product_name": "teilAuto Vielfahrertarif",
        "type": "subscription",
        "monthly_cost_eur": 30.0,
        "annual_cost_eur": 360.0,
        "discount_pct": 20.0,
        "travel_class": None,
        "coverage_scope": "selected_cities",
        "valid_modes": ["car_sharing"],
        "min_commitment_months": 12,
        "cancellation_notice_months": 1,
        "auto_renews": 1,
        "combinable_with": ["DT-49", "BC25-2", "BC50-2", "BC100-2"],
        "is_active": 1,
        "notes": "30 €/Monat + 25 € einmalig + 100 € Kaution. Kleine-Klasse: 1,92 €/h + 0,23 €/km (Rahmentarif −20 %). Kraftstoff im km-Preis inkl. Bis zu 4 Tarifpartner möglich.",
        "pricing_model": "per_km_and_time",
        "cost_per_minute_eur": round(1.92 / 60, 4),
        "cost_per_km_eur": 0.232,
        "unlock_fee_eur": None,
        "free_minutes_per_ride": None,
        "period_days": 30,
        "eligibility_min_age": 21,
        "eligibility_max_age": None,
        "eligibility_notes": "Führerschein erforderlich.",
        "city_availability": "Leipzig, Dresden, Halle, Erfurt, Magdeburg, Jena und weitere ostdeutsche Städte",
        "markdown_ref": "Markdownfiles Abos/Car Sharing/teilauto/teilauto_preise_tarife.md",
    },
]

# Ordered list of all columns for INSERT
COLUMNS = [
    "product_id", "product_name", "type",
    "monthly_cost_eur", "annual_cost_eur", "discount_pct",
    "travel_class", "coverage_scope",
    "valid_modes", "min_commitment_months", "cancellation_notice_months",
    "auto_renews", "combinable_with", "is_active", "notes",
    "pricing_model", "cost_per_minute_eur", "cost_per_km_eur",
    "unlock_fee_eur", "free_minutes_per_ride", "period_days",
    "eligibility_min_age", "eligibility_max_age", "eligibility_notes",
    "city_availability", "markdown_ref",
]


def _ensure_columns(conn) -> None:
    """Add new columns to subscription_products if they are missing (existing DBs)."""
    existing = {row[1] for row in conn.execute("PRAGMA table_info(subscription_products)")}
    for col_name, col_type in NEW_COLUMNS.items():
        if col_name not in existing:
            conn.execute(
                f"ALTER TABLE subscription_products ADD COLUMN {col_name} {col_type}"
            )


def seed_products() -> None:
    """Delete all subscription products and re-insert the full catalogue."""
    init_db()
    with get_conn() as conn:
        _ensure_columns(conn)
        # Disable FK checks temporarily so we can clear the catalogue even if
        # user_subscriptions rows still reference old product_ids.
        conn.execute("PRAGMA foreign_keys = OFF")
        conn.execute("DELETE FROM subscription_products")
        conn.execute("PRAGMA foreign_keys = ON")
        rows = []
        for p in PRODUCTS:
            row = []
            for col in COLUMNS:
                val = p[col]
                if isinstance(val, list):
                    val = json.dumps(val, ensure_ascii=False)
                row.append(val)
            rows.append(tuple(row))
        placeholders = ", ".join("?" * len(COLUMNS))
        col_names = ", ".join(COLUMNS)
        conn.executemany(
            f"INSERT INTO subscription_products ({col_names}) VALUES ({placeholders})",
            rows,
        )
    print(f"  {len(PRODUCTS)} subscription products seeded.")


if __name__ == "__main__":
    seed_products()
    print("Done.")
